# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/meghana7/projects/def-nicoleli/meghana7/IVDBM-ABM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/meghana7/projects/def-nicoleli/meghana7/IVDBM-ABM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Core/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meghana7/projects/def-nicoleli/meghana7/IVDBM-ABM/CMakeFiles /home/meghana7/projects/def-nicoleli/meghana7/IVDBM-ABM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meghana7/projects/def-nicoleli/meghana7/IVDBM-ABM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Nyvonna

# Build rule for target.
Nyvonna: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nyvonna
.PHONY : Nyvonna

# fast build rule for target.
Nyvonna/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyvonna.dir/build.make CMakeFiles/Nyvonna.dir/build
.PHONY : Nyvonna/fast

#=============================================================================
# Target rules for targets named ex_diffuse_temperature

# Build rule for target.
ex_diffuse_temperature: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ex_diffuse_temperature
.PHONY : ex_diffuse_temperature

# fast build rule for target.
ex_diffuse_temperature/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex_diffuse_temperature.dir/build.make CMakeFiles/ex_diffuse_temperature.dir/build
.PHONY : ex_diffuse_temperature/fast

#=============================================================================
# Target rules for targets named testRun

# Build rule for target.
testRun: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testRun
.PHONY : testRun

# fast build rule for target.
testRun/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRun.dir/build.make CMakeFiles/testRun.dir/build
.PHONY : testRun/fast

#=============================================================================
# Target rules for targets named Agent

# Build rule for target.
Agent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Agent
.PHONY : Agent

# fast build rule for target.
Agent/fast:
	$(MAKE) $(MAKESILENT) -f src/Agent/CMakeFiles/Agent.dir/build.make src/Agent/CMakeFiles/Agent.dir/build
.PHONY : Agent/fast

#=============================================================================
# Target rules for targets named FieldVariable

# Build rule for target.
FieldVariable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FieldVariable
.PHONY : FieldVariable

# fast build rule for target.
FieldVariable/fast:
	$(MAKE) $(MAKESILENT) -f src/FieldVariable/CMakeFiles/FieldVariable.dir/build.make src/FieldVariable/CMakeFiles/FieldVariable.dir/build
.PHONY : FieldVariable/fast

#=============================================================================
# Target rules for targets named World

# Build rule for target.
World: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 World
.PHONY : World

# fast build rule for target.
World/fast:
	$(MAKE) $(MAKESILENT) -f src/World/CMakeFiles/World.dir/build.make src/World/CMakeFiles/World.dir/build
.PHONY : World/fast

#=============================================================================
# Target rules for targets named Patch

# Build rule for target.
Patch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Patch
.PHONY : Patch

# fast build rule for target.
Patch/fast:
	$(MAKE) $(MAKESILENT) -f src/Patch/CMakeFiles/Patch.dir/build.make src/Patch/CMakeFiles/Patch.dir/build
.PHONY : Patch/fast

#=============================================================================
# Target rules for targets named ECM

# Build rule for target.
ECM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ECM
.PHONY : ECM

# fast build rule for target.
ECM/fast:
	$(MAKE) $(MAKESILENT) -f src/ECM/CMakeFiles/ECM.dir/build.make src/ECM/CMakeFiles/ECM.dir/build
.PHONY : ECM/fast

#=============================================================================
# Target rules for targets named ArrayChain

# Build rule for target.
ArrayChain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ArrayChain
.PHONY : ArrayChain

# fast build rule for target.
ArrayChain/fast:
	$(MAKE) $(MAKESILENT) -f src/ArrayChain/CMakeFiles/ArrayChain.dir/build.make src/ArrayChain/CMakeFiles/ArrayChain.dir/build
.PHONY : ArrayChain/fast

#=============================================================================
# Target rules for targets named Utilities

# Build rule for target.
Utilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Utilities
.PHONY : Utilities

# fast build rule for target.
Utilities/fast:
	$(MAKE) $(MAKESILENT) -f src/Utilities/CMakeFiles/Utilities.dir/build.make src/Utilities/CMakeFiles/Utilities.dir/build
.PHONY : Utilities/fast

#=============================================================================
# Target rules for targets named Diffusion

# Build rule for target.
Diffusion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Diffusion
.PHONY : Diffusion

# fast build rule for target.
Diffusion/fast:
	$(MAKE) $(MAKESILENT) -f src/Diffusion/CMakeFiles/Diffusion.dir/build.make src/Diffusion/CMakeFiles/Diffusion.dir/build
.PHONY : Diffusion/fast

examples/ex_diffuse_temperature.o: examples/ex_diffuse_temperature.cpp.o
.PHONY : examples/ex_diffuse_temperature.o

# target to build an object file
examples/ex_diffuse_temperature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex_diffuse_temperature.dir/build.make CMakeFiles/ex_diffuse_temperature.dir/examples/ex_diffuse_temperature.cpp.o
.PHONY : examples/ex_diffuse_temperature.cpp.o

examples/ex_diffuse_temperature.i: examples/ex_diffuse_temperature.cpp.i
.PHONY : examples/ex_diffuse_temperature.i

# target to preprocess a source file
examples/ex_diffuse_temperature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex_diffuse_temperature.dir/build.make CMakeFiles/ex_diffuse_temperature.dir/examples/ex_diffuse_temperature.cpp.i
.PHONY : examples/ex_diffuse_temperature.cpp.i

examples/ex_diffuse_temperature.s: examples/ex_diffuse_temperature.cpp.s
.PHONY : examples/ex_diffuse_temperature.s

# target to generate assembly for a file
examples/ex_diffuse_temperature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ex_diffuse_temperature.dir/build.make CMakeFiles/ex_diffuse_temperature.dir/examples/ex_diffuse_temperature.cpp.s
.PHONY : examples/ex_diffuse_temperature.cpp.s

examples/test_not_main.o: examples/test_not_main.cpp.o
.PHONY : examples/test_not_main.o

# target to build an object file
examples/test_not_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRun.dir/build.make CMakeFiles/testRun.dir/examples/test_not_main.cpp.o
.PHONY : examples/test_not_main.cpp.o

examples/test_not_main.i: examples/test_not_main.cpp.i
.PHONY : examples/test_not_main.i

# target to preprocess a source file
examples/test_not_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRun.dir/build.make CMakeFiles/testRun.dir/examples/test_not_main.cpp.i
.PHONY : examples/test_not_main.cpp.i

examples/test_not_main.s: examples/test_not_main.cpp.s
.PHONY : examples/test_not_main.s

# target to generate assembly for a file
examples/test_not_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testRun.dir/build.make CMakeFiles/testRun.dir/examples/test_not_main.cpp.s
.PHONY : examples/test_not_main.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyvonna.dir/build.make CMakeFiles/Nyvonna.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyvonna.dir/build.make CMakeFiles/Nyvonna.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyvonna.dir/build.make CMakeFiles/Nyvonna.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Agent"
	@echo "... ArrayChain"
	@echo "... Diffusion"
	@echo "... ECM"
	@echo "... FieldVariable"
	@echo "... Nyvonna"
	@echo "... Patch"
	@echo "... Utilities"
	@echo "... World"
	@echo "... ex_diffuse_temperature"
	@echo "... testRun"
	@echo "... examples/ex_diffuse_temperature.o"
	@echo "... examples/ex_diffuse_temperature.i"
	@echo "... examples/ex_diffuse_temperature.s"
	@echo "... examples/test_not_main.o"
	@echo "... examples/test_not_main.i"
	@echo "... examples/test_not_main.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

